### ISSUE TITLE
How can timezones be specified when asking for between dates?

### ISSUE THREAD

**Issue by vladnicula** [arolson101/rrule#2]
First of all, kudos on maintaining this library. Too bad the core one is currently abandoned. 

Let's say I have a recurrence rule for "Every first Monday of the month at 23:30" starting at `dtstart: x`. 

`First Monday` in UK starts at a different timestamp than `First Monday` in China. 

I'm implementing an application that would be able to switch between any given timezone, regardless of the browsers local timezone. 

I'm having a hard time figuring out how to specify the timezone for the `between` query. 

Am I looking at this the right way?

**Comment by arolson101** [comment]
The short answer is rrule doesn't currently support timezones, so you'd have to work around it yourself.  There's relevant discussion in https://github.com/jkbrzt/rrule/issues/38 and even a pull request (https://github.com/jkbrzt/rrule/pull/97).  I haven't looked into the pull request so I don't know what kind of shape it's in.

**Comment by arolson101** [comment]
I'm closing out rrule-alt.  Please move this to rrule.
