### ISSUE TITLE
Issues with dates before Jan 1, 1970

### ISSUE THREAD

**Issue by amcolash** [arolson101/rrule#4]
I have been working on a MagicMirror and have been contributing to one [project](https://github.com/MichMich/MagicMirror).

Recently there has been an issue with dates before 1970. There is an [issue](https://github.com/MichMich/MagicMirror/issues/791) for that project.

The issue is that the comment states that it is used so that dates are valid in JS. This cannot be true, since JS numbers can be really really big [source](http://stackoverflow.com/questions/27093130/how-to-get-the-minimum-and-maximum-date).

Could `ORDINAL_BASE` be changed to something more reasonable (like year 0 or even 1800)? I can make a PR if desired.

**Comment by polo2ro** [comment]
I got this problem on my project too

**Comment by arolson101** [comment]
I would accept a pr with test cases

**Comment by arolson101** [comment]
I'm closing out rrule-alt.  Please move this to rrule.
also I changed ORDINAL_BASE to 1900, and I agree, it could probably be year 1 like python
